### ISSUE TITLE
Breaks with rc2Hogfather

### ISSUE THREAD

**Issue by mtkirchner** [i-net-software/dokuwiki-plugin-siteexport#107]
PHP Warning:  include_once(/inc/plugincontroller.class.php): failed to open stream: No such file or directory in /lib/plugins/siteexport/preload.php on line 6
PHP Warning:  include_once(): Failed opening '/inc/plugincontroller.class.php' for inclusion (include_path='.:/opt/RZphp73/includes') in /lib/plugins/siteexport/preload.php on line 6
PHP Fatal error:  Uncaught Error: Class 'Doku_Plugin_Controller' not found in /lib/plugins/siteexport/preload.php:165
Stack trace:
#0 /inc/preload.php(9): include_once()
#1 /inc/init.php(26): include('/mnt/web519/e3/...')
#2 /doku.php(36): require_once('/mnt/web519/e3/...')
#3 {main}
thrown in /mnt/web519/e3/08/510261008/htdocs/igfwiki/lib/plugins/siteexport/preload.php on line 165

**Comment by gamma** [comment]
Please check todays version. I hope it is fixed, still supporting older versions.
