### ISSUE TITLE
Help, i'm not able to export :-(

### ISSUE THREAD

**Issue by poulpoulsen** [i-net-software/dokuwiki-plugin-siteexport#32]
hello,
i'm sure it is not a buginside the plugin, it is bug before the screen :-)
the following error occurs, if i want to export a wikipage.
Adding "garten:start" ( 1 / 1 )

[2015-02-28 16:44:26 ERROR] Sending request failed with error, HTTP status was '200'.

[2015-02-28 16:44:26 ERROR] http://localhost/dokuwiki/doku.php?id=garten:start&template=vector

[2015-02-28 16:44:26 ERROR] Runtime Error: Creating temporary download file failed for 'http://localhost/dokuwiki/doku.php?id=garten:start&template=vector'. See log for more information.

Here is the apache.log

[Sat Feb 28 16:23:43.305035 2015] [access_compat:error] [pid 3772:tid 1760] [client ::1:53743] AH01797: client denied by server configuration: C:/Users/Held/xampp/htdocs/dokuwiki/data/security.png, referer: http://localhost/dokuwiki/doku.php?id=garten:aussenlampe&do=admin
[Sat Feb 28 16:30:44.643670 2015] [access_compat:error] [pid 3772:tid 1760] [client ::1:53875] AH01797: client denied by server configuration: C:/Users/Held/xampp/htdocs/dokuwiki/data/security.png, referer: http://localhost/dokuwiki/doku.php?id=wiki:ebook&do=admin
[Sat Feb 28 16:30:44.966688 2015] [access_compat:error] [pid 3772:tid 1760] [client ::1:53875] AH01797: client denied by server configuration: C:/Users/Held/xampp/htdocs/dokuwiki/data/security.png, referer: http://localhost/dokuwiki/doku.php?id=wiki:ebook&do=admin
[Sat Feb 28 16:42:04.775199 2015] [access_compat:error] [pid 3772:tid 1760] [client ::1:54004] AH01797: client denied by server configuration: C:/Users/Held/xampp/htdocs/dokuwiki/data/security.png, referer: http://localhost/dokuwiki/doku.php?id=garten:planung_blauer_garten&do=admin
[Sat Feb 28 16:43:36.014990 2015] [access_compat:error] [pid 3772:tid 1744] [client ::1:54015] AH01797: client denied by server configuration: C:/Users/Held/xampp/htdocs/dokuwiki/data/security.png, referer: http://localhost/dokuwiki/doku.php?id=garten:start&do=admin
[Sat Feb 28 16:43:36.904046 2015] [access_compat:error] [pid 3772:tid 1744] [client ::1:54015] AH01797: client denied by server configuration: C:/Users/Held/xampp/htdocs/dokuwiki/data/security.png, referer: http://localhost/dokuwiki/doku.php?id=garten:start&do=admin

I think, that something is wrong inside my apache config, but i'm not sure.

Any help will be appreciated

Regards
Poul

Using xampp on win8.1 with latest dokuwiki release.

**Comment by gamma** [comment]
It looks like your web server is not allowed to load pages from the same server (client denied by server configuration). Can you check that? Have you checked google on this topic?

**Comment by poulpoulsen** [comment]
hallo,

i've think, that i configure xampp / apache / dokuwiki to be very open :-)
Dokuwiki tells, that there is a security risk (data directory is open 
from web).
Here is my httpd.conf
DocumentRoot "C:/Users/Held/xampp/htdocs"
<Directory "C:/Users/Held/xampp/htdocs">
     #
     # Possible values for the Options directive are "None", "All",
     # or any combination of:
     #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI 
MultiViews
     #
     # Note that "MultiViews" must be named *explicitly* --- "Options All"
     # doesn't give it to you.
     #
     # The Options directive is both complicated and important. Please see
     # http://httpd.apache.org/docs/2.4/mod/core.html#options
     # for more information.
     #
     Options Indexes FollowSymLinks Includes ExecCGI

     #
     # AllowOverride controls what directives may be placed in .htaccess 
files.
     # It can be "All", "None", or any combination of the keywords:
     #   AllowOverride FileInfo AuthConfig Limit
     #
     AllowOverride all
     Order allow,deny
     Allow from all
#    AllowOverride none

     #
     # Controls who can get stuff from this server.
     #
     Require all granted
</Directory>

Unfortunately i still get errors

[2015-03-02 14:22:26 ERROR] Sending request failed with error, HTTP 
status was '200'.

[2015-03-02 14:22:26 ERROR] 
http://localhost/dokuwiki/doku.php?id=start&template=vector

[2015-03-02 14:22:26 ERROR] Runtime Error: Creating temporary download 
file failed for 
'http://localhost/dokuwiki/doku.php?id=start&template=vector'. See log 
for more information.

How could i test to download?
Which location is used by sideexport?

Any idea?

Regards
Poul Poulsen




Am 02.03.2015 um 08:31 schrieb Gerry Weißbach:
> not allowed to load pages from the same server

**Comment by gamma** [comment]
Hi, what is the status of this? I just saw this seems to be open. Can you please check on the latest version?

**Comment by poulpoulsen** [comment]
Hi,
unfortunately it does not work with the newest version.
But i gave up, because i do not have any clue to fix this.
Probably it is something deeper inside my apache/dw/windows security configurations.
I don't know :-(

Regards
Poul Poulsen
