### ISSUE TITLE
Use with plugin:gallery

### ISSUE THREAD

**Issue by pmgeuze** [i-net-software/dokuwiki-plugin-siteexport#35]
Thank you for such a great plugin, it is saves me at least a week at the end of each of my case investigations.

The only issue that I am having difficulty with is using siteexport with plugin:gallery. When I export with the html render, I get the webpages and the gallery display with the thumbnails. When I click the thumbnails, the 'source' image is not the high resolution picture that he thumbnail comes from, but the now pixelated thumbnail.

I see that the images are exported as .jpeg when they are originally .jpg - I can see the workaround of copying over the original source images into the new siteexport folder and renaming them.

I would appreciate if there is a simple adjustment that allows the high resolution original images to be exported with the thumbnails from the plugin:gallery.

Thank you again.

**Comment by pmgeuze** [comment]
I have found an easier work around with the plugin:gallery. By using the lightbox option, it appears to trigger the siteexport to then save the high resolution image with the thumbnail.

Please disregard my initial request but leave this for others to find.

Again thank you.

**Comment by gamma** [comment]
Thaks for pointing out the issue. Since there seems to be a workaround I will not investigate further until there is more time for me to do so ;).
