### ISSUE TITLE
* is exported to Unordered List Item

### ISSUE THREAD

**Issue by mihadoo** [i-net-software/dokuwiki-plugin-siteexport#42]
siteexport fails to export the following correctly to html:
  * TEST 1
  * TEST 2

The above is exported to the following in html:
* Unordered List ItemTEST 1
* Unordered List ItemTEST 2

**Comment by gamma** [comment]
is the text rendered into the output? I have not seen this until now. the string "Unordered List Item" is nowhere to be found in the site export sources.

**Comment by mihadoo** [comment]
I am sorry. The text "Unordered List Item" was already in the dokuwiki page. I think that it must come from pasting the text from an HTML editor... I am sorry, I overlooked this somehow, you can close this.

**Comment by aj203355** [comment]
@gamma Any chance you could tell me how to exclude a single page or multiple pages when performing a multi-export with the siteexport plugin?

**Comment by gamma** [comment]
@aj203355 please see your issue.
