### ISSUE TITLE
Trouble with links in offline dokuwiki pages 

### ISSUE THREAD

**Issue by Makerthone** [i-net-software/dokuwiki-plugin-siteexport#43]
Hello again!
This time i hope that somebody will answer me.
My problem is:
When i do export pages and after this try open links in that offline pages, link path of page to the same page that already open.
e.g. i open html page "start" and this page have link to the page "programms", when i place cursor on link "programs" i see path to the current page "start" instead of path to the "programms"
Result -> i can't open links in my offline pages

**Comment by gamma** [comment]
Sorry for being on paternal leave....
I'll check when I get back.

**Comment by Makerthone** [comment]
Thx man)

**Comment by gamma** [comment]
do you have any rewrite options enabled? which is the backend server/OS of your DW?

**Comment by Makerthone** [comment]
Do you mean the "userewrite" option in DW admin tab? Yes.The value it is - "Dokuwiki internal"

After changing the value to "none" all is ok

Very thx! You are the best!:)
