### ISSUE TITLE
siteexport breaks indexer?

### ISSUE THREAD

**Issue by lesteff** [i-net-software/dokuwiki-plugin-siteexport#45]
It lookslike siteexport make dokuwikis indexing mechanism unusable. I didn't had tim to troubleshoot inside of sit export (yet) - if I disable siteexport it works fine again. 

it can be easily reproduced  by hiting the indexer via  cli: 
```
root@wiki:/var/www# php5 bin/indexer.php 
PHP Fatal error:  Call to a member function process_event() on a non-object in /var/www/wiki.be.nts.ch/inc/events.php on line 70
```

dokuwiki-2015-08-10a

**Comment by gamma** [comment]
Ok, i can reproduce the problem but a quick check did not reveal the source. I'll check on this.

**Comment by gamma** [comment]
So the problem comes from the cron component. I'm not aware of anyone using it ... I guess it could be removed.

**Comment by gamma** [comment]
See f44c759a20e24a9b69102e89c331188212327815 - I removed the cron functions
