### ISSUE TITLE
siteexport > issue excluding a single page or multiple pages

### ISSUE THREAD

**Issue by aj203355** [i-net-software/dokuwiki-plugin-siteexport#47]
@gamma 

Any chance you could tell me how to exclude a single page or multiple pages when performing a multi-export with the siteexport plugin? When the original owner of the dokuwiki site deployed the server, he didn't organize the namespace at all, so I can't use the namespaces as a way to break up the export jobs. I'm running into issues with a few pages during the export (404 errors for missiing components) which is causing the entire job to fail.

By the way, thank you for the time and energy you have given to make this plugin and provide support. It's very much appreciated.

**Comment by gamma** [comment]
Hey, it currently not possible to exclude pages. Did you try to set the option to ignore non-200 codes? This should make the job go on.

**Comment by aj203355** [comment]
Yeah I did...problem was dokuwiki was running on windows using
IIS....horrible...so plug in completed successfully when I migrated over to
Linux and apache (go figure, Linux software runs better on linux).
