### ISSUE TITLE
Error in line 665 in inc/functions.php

### ISSUE THREAD

**Issue by wernerflamme** [i-net-software/dokuwiki-plugin-siteexport#52]
Since some hours, I get an error on my logs:
`PHP Fatal error:  Can't use method return value in write context in /srv/www/linux/dokuwiki/lib/plugins/siteexport/inc/functions.php on line 665`

In my file, this line reads:
`if ( count($baseParts) == $originalBasePartsCount && $existingPageID != null && !empty( $this->getConf("offSiteLinkTemplate") ) ) {`

I'm running DokuWiki on PHP 5.3.17 on SLES 11 SP4. The plugin was updated first in August, 2015, and updated last "Thu, 31 Mar 2016 01:07:02 +0000". The errors start 2 minutes later :(

**Comment by gamma** [comment]
Sorry for the inconvenience. Please update and check, I made a hot fix for the issue.

**Comment by wernerflamme** [comment]
Yes, it works :)
Sorry for using this old PHP version, but SLES 11 does not provide newer ones - as long as one needs support.
