### ISSUE TITLE
siteexport_pdf render engine, images not included

### ISSUE THREAD

**Issue by Kyhel** [i-net-software/dokuwiki-plugin-siteexport#53]
I'm using the plugin to export in PDF the whole wiki, but in place of the images, I get a little square with a red cross. Since when trying to export in PDF with the plugin Dw2Pdf disabled, the plugins asks for it to be enabled, I assume even when trying to export the wiki, and selecting the render engine siteexport_pdf, it still uses Dw2Pdf.

I've tried exporting with the dw2pdf render engine, and the images are present.

Has anyone an idea of why the images are not included, and how to try to fix it ?

**Comment by gamma** [comment]
What kind of images are missing? Default ones, plugin images or Images you uploaded with the content?

Please check your configuration -> site export section. There is an exclude for certain paths. Are these missing or even more?

**Comment by Kyhel** [comment]
The images that are missing are included in the pages using the syntax ``{{namespace:filename|tooltip_text}}``. I've uploaded them using the "multimedia manager" (I'm not sure about the name, my wiki is in French) in the same namespace as the page. They are the only missing images. The dokuwiki logo for example is present.

In the configuration the plugin»siteexport»exclude parameter is empty.
Every parameter is with the default value.

Thanks for your time,
Cheers,
Kyhel

**Comment by gamma** [comment]
Hey Kyhle, I made some changes since the site export had problems with the mpdf v6 release in DW2PDF. Can you please check if this issue is resolved?

**Comment by Kyhel** [comment]
Hey, 
I'm no longer working on the project anymore, and the wiki's images that used to cause a problem are no longer available on the wiki, so I can't test it sorry. We might as well close this issue and I'll reopen it if I find a way to reproduce the problem.

Cheers

**Comment by gamma** [comment]
Ok, no problem.
