### ISSUE TITLE
Export not working, not paths for,,,

### ISSUE THREAD

**Issue by rgleason** [i-net-software/dokuwiki-plugin-siteexport#64]
Start Process
Direct Download Link:
wget Download URL:
curl Download URL:

It used to have those paths. What should I do? Have uninstalled and reinstalled.
It completed before with paths in the fields above, but did not give me the full namespace and down...
I would appreciate a more complete description of how to set this up so that it works.

Thanks

**Comment by gamma** [comment]
Are there any JS errors in the Browser console?

**Comment by rgleason** [comment]
The message is "Finished but download failed."

**Comment by gamma** [comment]
have you had a look at the console? This message should be visible in the browser when you tried a download ...

**Comment by rgleason** [comment]
I am using Firefox, when I go to Tools > Web Developer > Web Console the console appears. When I then get onto the dokuwiki page and hit start...Ok I got some results in the Console. I will try to attach it.
[OpenCPN-Dokuwiki.txt](https://github.com/i-net-software/dokuwiki-plugin-siteexport/files/553149/OpenCPN-Dokuwiki.txt)

Thank you for helping!

**Comment by gamma** [comment]
That looks good so far ... could you send me an email with a Login that has admin power to our support email address? I'd like to check directly if possible? (please create an extra account that you can delete afterwards. and please do not post the data here ;))

**Comment by rgleason** [comment]
Yesm gamma, where do I find the support email? Is it github?

**Comment by gamma** [comment]
please use tools@inetsoftware.de

**Comment by rgleason** [comment]
Ok, just found it on the Dokuwiki Site Manager page.

**Comment by rgleason** [comment]
Done

**Comment by gamma** [comment]
You DW looks good and the request are going through, but there is never a response. It looks like something is either catching the AJAX_CALL_UNKNOWN event and not forwarding it (could be a plugin) or something else on the server is preventing the output to be send back to the client (ajax.php)

You should try to disable either plugin by plugin or as many plugins as possible to check if that will change something. If you have command line access to the server you could also try to `grep -R AJAX_CALL_UNKNOWN .` in the lib/plugins directory and check if any of the plugs does something with that event, preventing it from executing up to the site export plugin ...

**Comment by rgleason** [comment]
Thank you Gerry. I'll try those things.

**Comment by rgleason** [comment]
I understand very little, but am trying.
It is on line 46   https://github.com/i-net-software/dokuwiki-plugin-siteexport/blob/master/action/ajax.php

Did a search on "grep -R AJAX CALL UNKNOWN"

https://vanillaforums.org/discussion/27720/event-hooks-documentation
"You can do a search for "FireEvent" in the source (and also for EventArguments)"
https://github.com/vanilla/vanilla/search?utf8=%E2%9C%93&q=EventArguments+FireEvent

https://www.dokuwiki.org/devel:event:ajax_call_unknown#plugins_handling_this_event

**Comment by rgleason** [comment]
I read that the plugin indexmenu uses this too.

**Comment by rgleason** [comment]
There is an export script 
https://www.dokuwiki.org/tips:offline-dokuwiki.sh?s

What do you think?

**Comment by gamma** [comment]
I guess this is probably working too.

I'm sorry, I'm lost - the next step would be trying to add debug code to the plugin registration ... but that is up to you I'm afraid.

**Comment by rgleason** [comment]
Thanks. I am going to think about this a little.

**Comment by rgleason** [comment]
Gerry  What is this for? and where is it put?  Is it necessary or is it useful?
https://scrutinizer-ci.com/g/i-net-software/dokuwiki-plugin-siteexport/code-structure/master/operation/%2Bglobal%5Caction_plugin_siteexport_ajax%3A%3A__init_functions

**Comment by gamma** [comment]
I'm not sure where you are heading. The init function is necessary to connect the ajax.php with basically everything in the inc folder.

**Comment by alexander-vidoni** [comment]
Hi @gamma, @rgleason 

I had an error quite similar to yours perhaps.
I deleted the three standard wiki pages below the namespace **wiki**.
The site export function creates an intermediate file (the zip file) and tries to store it under that namespace ("wiki").

`/lib/exe/fetch.php?cache=nocache&siteexport=d219cf60c4aba4f9e57144281e121781&media=`**wiki:siteexport.zip**

Due to my prior deletion of that namespace -> **storing the intermediate file** fails.
I think the namespace (wiki) **must** exist for this plugin to make it work.

**My solution:** create a page link like this:

 `[[wiki:dummypage|Link to my dummy page, only to have a namespace for the intermediate zip file for site export]]`

Clilck that link and create the page with content: 

> Arrrrrrrrrrrggggghhh - Four hours wasted on a rainy in November!

Save the page and try to run the export again.
Good luck.

**Comment by gamma** [comment]
I'm sorry you had to go through this pain. But thanks for sharing!!!

You could check the settings of SiteExport in the Admin-Configuration. There should be an entry for the path to put the siteexport.zip files for download. It should work to move this path to a different namespace if you do not have/want the original paths to exists.

**Comment by alexander-vidoni** [comment]
Thank you for your support an developing this plugin.

One problem to detect the error was that someone used the '@' symbol in 

> fetch.php

 to supress error message of 

> file_get_contents()

So, no log entry was generated in the **php_errors.log** file.

**IMHO**: it would be better not to use the @ symbol, so debugging is more easy.

**Comment by rgleason** [comment]
Under config  > siteexport plugin
plugin»siteexport»zipfilename  
Wiki Path and name for exported ZIP file
 ----> was  start:siteexport.zip
 ----> now opencpn:siteexport.zip   (my 4 wiki books are in this location)
Saved the config at the bottom.
Then went to a page and where the edit button is, down lower, selected Export. 
A zip file popped up and prompted for download to the PC.

Viewed a page I had created ":opencpn:fullindex"  where I had entered this index request

Then selected the Export from the side menu, and changed the settings to export the entire linked document.
Set Namespace:  opencpn:opencpn_user_manual
Parent Namespace to export: opencpn:opencpn_user_manual
Export Type: specified depth    <---was single page
Depth:  5

The result was each page was saved to a zip file, which took a little while  (with progressmessages)
Then a prompt appeared to view the zip or download it to the pc.  I downloaded 16mb zip will now expand it and view it.

**Comment by rgleason** [comment]
This is working!   Its not perfect for our purposes, but it gets us within reach.

In the page "fullindex"  we have the following:
```
{{indexmenu_n>100}}
{{indexmenu>:opencpn:opencpn_user_manual#1|js#drktheme navbar msort nsort}}
<nowiki>==========</nowiki>
{{indexmenu>. | notoc nojs}}
```

The bottom one works, showing the pages, but the top one does not (no links). Is this because it uses javascript?  How would you suggest that we export sorted single page html (easily)?

Also since this is a help file, it would be nice to be able to search it.

Thank you Alexander and Gerry!

**Comment by gamma** [comment]
Great that it works now! I do not know how the index menu works with javascript, but it is likely not to work in your case. It will probably try to load the pages and index via ajax which is not available offline. I'd suggest a multipage export with an index without JavaScript. But then it is not searchable.

**Comment by rgleason** [comment]
Gerry, what is a multipage export?  Sorry, language/understanding. 

Also I'd like to simplify the export so that it is just the pages and not the wiki too. Please see the attached, for your understanding. (eliminate the outer index and the wiki headers/footers, etc) 
The goal is to create a single file html "Book" indexed in approximately the order that this indexmenu gives us:
`{{indexmenu>:opencpn:opencpn_user_manual#1|js#drktheme navbar msort nsort}}`
best seen here  http://tgp-architects.com/dokuwiki/doku.php?id=opencpn:opencpn_user_manual

OpenCPN User Manual  is one of 4 books we'd like to export. The navigation might get better when we get previous and next working in the footer, but right now its a little awkward.
![siteexport-zip-expanded-in-browser](https://cloud.githubusercontent.com/assets/2363959/20102072/b53b4d1a-a592-11e6-865d-30e07c24c5e3.jpg)


Do you have any suggestions for how to accomplish this?

**Comment by rgleason** [comment]
Would we do something like this?
{{indexmenu>opencpn:opencpn_user_manual:getting_started | notoc nojs}}
{{indexmenu>opencpn:opencpn_user_manual:toolbar_buttons | notoc nojs}}{{indexmenu>opencpn:opencpn_user_manual:menubar | notoc nojs}}
{{indexmenu>opencpn:opencpn_user_manual:charts | notoc nojs}}

And put it in the exact order that we want?

**Comment by gamma** [comment]
You could use a "toc" - page in the namespace. see https://github.com/i-net-software/dokuwiki-plugin-siteexport#table-of-contents-definition - With `<toc merge> ... </toc>` But you'd have to define the structure and every page by hand.

**Comment by rgleason** [comment]
Ok, how do I eliminate the wiki shell and extra navigation menu?  
Would that be resolved by a line by line "toc"  of every page?
--This is a lot of work to make and maintain. I wonder if there is a script that could take the outline that we have for 

`{{indexmenu>:opencpn:opencpn_user_manual#1|js#drktheme navbar msort nsort}}`

and just turn it into a line by line TOC?

**Comment by gamma** [comment]
The look of your exported pages depends on your template. You will have to modify it or use a template that suits your needs. As for the TOC File: yeah, that would be nice. Not sure if "siteexportAGGREGATOR" (see documenation) could help here ...

**Comment by rgleason** [comment]
Thanks, Ok,

1. To eliminate the Wiki Shell and doubled left navigation :  We would need to make a modified template and reference that template.
2. How to turn the {{indexmenu ...}}  navigation and sorting into a line by line TOC  Ok I'll look at siteexportAggregator.
3.

**Comment by rgleason** [comment]
I'm back working on this again, and have had some success exporting both  pdf and html (cgkedit).  

I am learning a bit about selecting the three controls (page, specified depth and namespace and below)
Is the specified depth measured from the  Set namespace or from Parent Namespace to export?
I am a little confused what the difference it.

Also it would be nice if we could specify.  
Do not include blank pages and namespaces with only blank pages.  checkbox

I've been having trouble completing a full siteexport and the most I've achieved is 104/408
but most of the time it is about 55/408. The expanding blue line stops and it just sits....

 I've got debug on and a file under :opencp:debug.txt and nothing seems to be written in it.  I tried firebug on the site export page to find AJAX errors but have not found any yet.
Any suggestions?

Right now I am trying an export with all checkboxes to turn off java on plugins. It seems faster.

What I've found is that the pdf export works well, putting individual pages for each namespace under various directories.  The pdf is searchable.

Regarding the html appears to work with a browser loading each page, and each page appears to be located in its associated directory.  The images all show fine. My problem is determining if these individual htmls are all linked together and also we really need a linked TOC at the top of a single html document (or muitiple html documents under various directories as long as it is easy for users).

Can you give me any guidance on the best way to approach this?

Ps  We are using IndexMenu Plugin and it seems to be working with SiteExport (except it hasnt completed) and we don't end up with a Linked TOC at the top for navigation. 

This is just an idea, but I could put  a  "IndexMenu Plugin"  TOC line at the top of the first page so we get that linked TOC we want.   Would that work?

Sorry about all the questions, but when I get it working I will write up details for how it works with IndexMenu for others.  

Thanks.

**Comment by rgleason** [comment]
By the way I sent login info for the site opencpn.org    click on "Books" 
We are trying to export the Opencpn User Manual 
1. To a single or multiple html that is easy for user to move around in.
2. With a navigatible TOC at the top.  (Will try putting the Indexmenu code at the top..)

I wonder what is causing the glitch at 54-108 pages.   
Its now saved 104/376 ....

**Comment by rgleason** [comment]
PS: I forgot that I have "FllIndex"  page here
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:fullindex

Wouldn't that provide a linked TOC in the final document?

**Comment by rgleason** [comment]
Users can look at an example that should be working
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:edit_user_manual:site_export_plugin

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:edit_user_manual:test_navigation_toc#siteexport_pluginopencpn_user_manual_toc

Closing this
