### ISSUE TITLE
Exclusions:  Lib files   - Why are these here?

### ISSUE THREAD

**Issue by rgleason** [i-net-software/dokuwiki-plugin-siteexport#73]
After Export the siteexport.zip contains:
..\lib\exe\css.php.t.bootstrap3.css
..\lib\exe\js.php.bootstrap3.js
..\lib\exe\opensearch.html

What do these files do? 
Why are they exported?
Is the css used by the exported html files?
How do we exclude these files? 
I don't believe the plugin has access to these files.

Thanks very much for your help.

**Comment by gamma** [comment]
These are "standard" files, linked in the meta header section. You can either modify the template to exclude them or you can use the global exclude option in the admin settings of the plugin.

**Comment by rgleason** [comment]
Thankyou Gerry
