### ISSUE TITLE
OpenCPN.org export

### ISSUE THREAD

**Issue by bdbcat** [i-net-software/dokuwiki-plugin-siteexport#74]
Working on OpenCPN.org export...

1.  Where is the debug log file located?  I specify opencpn:debug2.txt, with log level "info".  I cannot find the file.

2.  What is the exact syntax of the "exclusion" field in the preferences?  I try ".gov", to exclude references off-site, and this does not seem to work.

Thanks
Dave

**Comment by gamma** [comment]
* The log file is located in the media folder. In your case it should be the opencpn namespace.
  * Exclude can be a series of Regex Patterns, separated by spaces. Offsite references should not be exported but only linked - but they have to start with `http/s`, `mailto:`, `javascript:` or `data:`

**Comment by rgleason** [comment]
Thank you Gerrry
