### ISSUE TITLE
Blank page issue/feature (due to Indexmenu sorting namespaces separately from pages)

### ISSUE THREAD

**Issue by rgleason** [i-net-software/dokuwiki-plugin-siteexport#76]
We would like to remove all "blank.html" and the "parent namespace" as a filter to the export, so that this does not have to be done by hand.  It should possibly be an option with checkbox.  We need to keep the blank pages in the wiki.

Remove all "blank.html" and provided there is just that file in the directory, remove the parent namespace .
-"Checkbox"

================
Problem: Blank.html pages that are under an otherwise empty namespace, are being exported. We would like to avoid that if possible.

When I do a search in the wiki search bar for  "blank"  Result: 45 lines  x 4 cols = 180 blank pages.

https://opencpn.org/wiki/dokuwiki/doku.php?do=search&id=blank

I picked one of them and it happened to be

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:edit_user_manual:indexmenu_plugion:blank

I opened it and deleted the text "This page intentionally left blank" . When building the wiki this was done for each page that did not sort properly,  to create a "blank" sub-page so that indexmenu plugin would be able to sort properly.   {This action forces the "page" to become a "namespace" so all pages are actually "namespaces" and thus sorted in the same way by indexmenu.)

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:edit_user_manual:indexmenu_plugion:this_page_intentionally_left_blank

Note: If we delete the text in the blank sub-page "This page intentionally left blank", and hit "enter", the sub-page will be removed automatically "this page does not exist" along with the namespace, and the parent page will no longer sort properly. Look at the left navigation index for Indexmenu Plugin down under Editor Manual, under Test Questions.  The code at the top of the page says " Indexmenu sort number: 3"  or {{indexmenu_n>3}}  so this page is intended to be #3 underneath Editor Manual!
When the blank page is removed, the parent page dropped out of the sort order due to the way indexmenu sorts namespaces first and then pages!

So how do we get rid of these 200 instances of blank pages and associated namespaces?

They all should be named with "blank" at the end!!

https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:user_corner:blank

-- So we need to do a Regex search on "blank" pages and delete them in a cache and not in the dokuwiki documents!

- We also need to delete the parent directory of that "blank.html" no matter what the name is (they all have different names associated with the name of the parent page.

Could this a filter applied just before writing to siteexport.zip on the server ?

Could it have a checkbox under the SiteExport Plugin?

- Perhaps this already exists in some form....?

We do NOT want to delete the blank pages on the wiki as that will mess up the sort order.

**Comment by rgleason** [comment]
Another way:

Could there be an exclude wildcard for all "blank"  or "whatever...labeled" pages
Then a checkbox to exclude all empty directories, run after the "blank" pages are filtered

**Comment by gamma** [comment]
Did you try the global exclude option?

**Comment by rgleason** [comment]
OK how would you use the global exclusion?
Exclude all "..ns:blank"
Exclude all empty parent directories to "..:ns;blank"

I am unsure how you would express this properly.

**Comment by rgleason** [comment]
Closing
