### ISSUE TITLE
BUG: Single Page Exports show the Dokuwiki mobile interface, multipage exports do not.

### ISSUE THREAD

**Issue by rgleason** [i-net-software/dokuwiki-plugin-siteexport#96]
It is intended, I believe that exports be compatible with mobile standards. Single page exports show the typical Mobile Responsive Interface, however multiple page exports do not. Instead it is a clunky interface without the advantage of 
1. Search
2. Mobile Responsive
3. Sidebar - Indexmenu which is responsive too.
4. Navigation such as  "You are Here" and "Trace" which are an important part of the Dokuwiki standard.

Please see the attached, which is the output html that SiteExport should produce.

**### SINGLE NS EXPORT - LAPTOP**
![o-manual-laptop-browser](https://user-images.githubusercontent.com/2363959/44497243-4af08b80-a646-11e8-8bc7-071ae29ecd7b.png)

### **SINGLE NS EXPORT - PHONE EXPANDED**
![o-manual-phone-search-2](https://user-images.githubusercontent.com/2363959/44497256-5643b700-a646-11e8-86b1-82b900eaa74d.png)

### **SINGLE NS EXPORT - PHONE**
![o-manual-phone-1](https://user-images.githubusercontent.com/2363959/44497262-5cd22e80-a646-11e8-8171-4b584610ad20.png)

Here is what a multiple page document looks like:
It lacks all the advantages of the Dokuwiki interface.

### **MULTIPLE NAMESPACE EXPORT RESULT**
![screenshot 215](https://user-images.githubusercontent.com/2363959/44497310-9014bd80-a646-11e8-991a-5226b80a4e08.png)

**Comment by gamma** [comment]
The issue is very old; I have no idea, what exactly is going wrong, but I'd recommend using a custom template that is as simple as possible.
